version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/web"
    schedule:
      interval: "daily"
