version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/web"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "pip"
    directory: "/notifier"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/gh-pages"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/bot"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/notifier"
    schedule:
      interval: "weekly"
