version: '3.9'

services:
  bot:
    build: ./bot
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - ${BOT_API_PORT}:${BOT_API_PORT}
    restart: unless-stopped
    container_name: anisearch-bot
  web:
    build: ./web
    env_file:
      - ./.env
    depends_on:
      - db
      - bot
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: unless-stopped
    container_name: anisearch-web
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: anisearch-db

volumes:
  pgdata: