version: '3.9'

services:
  bot:
    build: ./bot
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - '8765:8765'
    restart: unless-stopped
    container_name: anisearch-bot
  web:
    build: ./web
    env_file:
      - ./.env
    depends_on:
      - db
      - bot
    ports:
      - '8080:8080'
    restart: unless-stopped
    container_name: anisearch-web
  asuka:
    build: ./asuka
    env_file:
      - ./.env
    depends_on:
      - db
      - bot
    restart: unless-stopped
    container_name: anisearch-asuka
  db:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: anisearch-db

volumes:
  pgdata: